import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { HomeLink } from "./components/HomeLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "sandbox next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="static/favicon.ico" sizes="any" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
